# Generated by Django 6.0 on 2026-02-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ordercategory_table'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLanguagePairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.languagepair')),
            ],
            options={
                'db_table': 'editor_language_pairs',
            },
        ),
    ]
