# Generated by Django 6.0 on 2025-12-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('translators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='OrderTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_page', models.FloatField(blank=True, null=True)),
                ('price_per_action', models.FloatField(blank=True, null=True)),
                ('currency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('language_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.languagepair')),
            ],
            options={
                'db_table': 'order_traffic',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=10, verbose_name='Пріоритет')),
                ('accepted_at', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('flex_deadline', models.BooleanField(default=False)),
                ('page_count', models.FloatField(default=0)),
                ('symbols_count', models.IntegerField(default=0)),
                ('client_comment', models.TextField(null=True)),
                ('translator_comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('editor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_orders', to=settings.AUTH_USER_MODEL)),
                ('language_pair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.languagepair')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
                ('translator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translators.translator')),
                ('translator_traffic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translators.translatortraffic')),
                ('traffic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertraffic')),
                ('client_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_status_orders', to='orders.status')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_status_orders', to='orders.status')),
                ('translator_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_status_orders', to='orders.status')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
