# Generated by Django 6.0 on 2025-12-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(choices=[('translator', 'Перекладач'), ('client', 'Клієнт'), ('editor', 'Редактор')], default='translator', max_length=20)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('expire_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('banned_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='orders.order')),
            ],
            options={
                'db_table': 'order_links',
            },
        ),
    ]
