# Generated by Django 6.0 on 2025-12-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLink',
        ),
    ]
