# Generated by Django 6.0 on 2025-12-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(choices=[('translator', 'Translator'), ('client', 'Client'), ('editor', 'Editor')], max_length=20)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('banned_to', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='orders.order')),
            ],
            options={
                'db_table': 'order_links',
            },
        ),
    ]
