# Generated by Django 6.0 on 2025-12-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('orders', '0004_orderlink'),
        ('translators', '0004_rename_translator_id_translatortraffic_translator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flex_deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='order',
            name='symbols_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='translator_comment',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.ForeignKey(db_column='client_status', on_delete=django.db.models.deletion.CASCADE, related_name='client_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='editor_id',
            field=models.ForeignKey(db_column='editor_id', on_delete=django.db.models.deletion.CASCADE, related_name='edited_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='language_pair_id',
            field=models.ForeignKey(db_column='language_pair_id', on_delete=django.db.models.deletion.CASCADE, to='core.languagepair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_id',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='general_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='traffic_id',
            field=models.ForeignKey(db_column='traffic_id', on_delete=django.db.models.deletion.CASCADE, to='orders.ordertraffic'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_id',
            field=models.ForeignKey(db_column='translator_id', on_delete=django.db.models.deletion.CASCADE, to='translators.translator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_status',
            field=models.ForeignKey(db_column='translator_status', on_delete=django.db.models.deletion.CASCADE, related_name='translator_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_traffic_id',
            field=models.ForeignKey(db_column='translator_traffic_id', on_delete=django.db.models.deletion.CASCADE, to='translators.translatortraffic'),
        ),
    ]
