# Generated by Django 6.0 on 2025-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_accepted_at_remove_order_client_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flex_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='page_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=10, verbose_name='Пріоритет'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbols_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='translator_comment',
            field=models.TextField(null=True),
        ),
    ]
