# Generated by Django 6.0 on 2026-01-16 09:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_accepted_at_order_client_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 16, 9, 28, 39, 297651, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('client_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_client_statuses', to='orders.status', verbose_name='Статус для клієнта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Замовлення')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_main_statuses', to='orders.status', verbose_name='Загальний статус')),
                ('translator_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_translator_statuses', to='orders.status', verbose_name='Статус для перекладача')),
            ],
            options={
                'verbose_name': 'Історія статусів',
                'verbose_name_plural': 'Історія статусів',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
