# Generated by Django 6.0 on 2025-12-24 19:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_created_at_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEditorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.TextField(verbose_name="Коментар рев'ю")),
                ('review_status', models.CharField(choices=[('rejected', 'Відхилено'), ('approved', 'Прийнято')], default='rejected', max_length=20, verbose_name="Статус рев'ю")),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перевірки')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_reviews', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': "Рев'ю редактора",
                'verbose_name_plural': "Рев'ю редакторів",
                'db_table': 'order_editor_review',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до оцінки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оцінювання')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='orders.order', verbose_name='Замовлення')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оцінювач')),
            ],
            options={
                'verbose_name': 'Оцінка якості',
                'verbose_name_plural': 'Оцінки якості',
                'db_table': 'translation_quality',
            },
        ),
    ]
