# Generated by Django 6.0 on 2026-01-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_created_at_file_ordereditorreview_and_more'),
        ('orders', '0008_ordereditorreview_translationquality'),
    ]

    operations = [
    ]
