# Generated by Django 6.0 on 2026-01-27 09:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordercategory'),
        ('orders', '0009_merge_20260126_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сума для клієнта'),
        ),
        migrations.AddField(
            model_name='ordertraffic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tariffs', to='core.ordercategory'),
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
    ]
