# Generated by Django 6.0 on 2026-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='category',
            field=models.CharField(choices=[('general', 'Загальний'), ('client', 'Для клієнта'), ('translator', 'Для перекладача'), ('editor', 'Для редактора')], default='general', max_length=20, verbose_name='Категорія статусу'),
        ),
    ]
