# Generated by Django 6.0 on 2026-02-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_status_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
