# Generated by Django 6.0 on 2026-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_options_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
