# Generated by Django 6.0 on 2026-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertraffic',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
