# Generated by Django 6.0 on 2026-04-22 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='order',
            name='manager_accept_id',
            field=models.ForeignKey(db_column='manager_accept_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='manager_delivery_id',
            field=models.ForeignKey(blank=True, db_column='manager_delivery_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
