# Generated by Django 6.0 on 2026-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_manager_id_order_manager_accept_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symbols_with_spaces_count',
            field=models.IntegerField(default=0, verbose_name='Символи з пробілами'),
        ),
    ]
