# Generated by Django 6.0 on 2026-04-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_symbols_with_spaces_count'),
        ('translators', '0009_translator_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationquality',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translators.translator', verbose_name='Оцінювач'),
        ),
    ]
