# Generated by Django 6.0 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_translationquality_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='images_count',
            field=models.IntegerField(default=0, verbose_name='Кількість зображень'),
        ),
    ]
