# Generated by Django 6.0 on 2026-06-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_images_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='editor_status',
            field=models.ForeignKey(blank=True, db_column='editor_status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_status_orders', to='orders.status'),
        ),
    ]
