# Generated by Django 6.0 on 2026-07-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_category_alter_client_email_and_more'),
        ('core', '0007_alter_languagepair_source_language_and_more'),
        ('orders', '0021_order_editor_status'),
        ('translators', '0013_remove_translator_currency_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.ForeignKey(db_column='client_status', on_delete=django.db.models.deletion.PROTECT, related_name='client_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='editor_id',
            field=models.ForeignKey(db_column='editor_id', on_delete=django.db.models.deletion.PROTECT, related_name='edited_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='editor_status',
            field=models.ForeignKey(blank=True, db_column='editor_status', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language_pair_id',
            field=models.ForeignKey(db_column='language_pair_id', on_delete=django.db.models.deletion.PROTECT, to='core.languagepair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_accept_id',
            field=models.ForeignKey(db_column='manager_accept_id', on_delete=django.db.models.deletion.PROTECT, related_name='accepted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_delivery_id',
            field=models.ForeignKey(blank=True, db_column='manager_delivery_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='general_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='traffic_id',
            field=models.ForeignKey(db_column='traffic_id', on_delete=django.db.models.deletion.PROTECT, to='orders.ordertraffic'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_id',
            field=models.ForeignKey(db_column='translator_id', on_delete=django.db.models.deletion.PROTECT, to='translators.translator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_status',
            field=models.ForeignKey(db_column='translator_status', on_delete=django.db.models.deletion.PROTECT, related_name='translator_status_orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_traffic_id',
            field=models.ForeignKey(db_column='translator_traffic_id', on_delete=django.db.models.deletion.PROTECT, to='translators.translatortraffic'),
        ),
    ]
