# Generated by Django 6.0 on 2025-12-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_for_pairs', to='core.language')),
                ('target_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_for_pairs', to='core.language')),
            ],
            options={
                'db_table': 'language_pairs',
            },
        ),
    ]
