# Generated by Django 6.0 on 2026-02-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactioncategory_transaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='transactioncategory',
            table='transaction_category',
        ),
    ]
