# Generated by Django 6.0 on 2026-02-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordercategory',
            table='order_category',
        ),
    ]
