# Generated by Django 6.0 on 2026-05-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepair',
            name='source_language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='source_pairs', to='core.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languagepair',
            name='target_language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='target_pairs', to='core.language'),
            preserve_default=False,
        ),
    ]
