# Generated by Django 6.0 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='salary',
            table=None,
        ),
    ]
