# Generated by Django 6.0 on 2026-04-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_end_date_salary_start_date_alter_salary_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='period',
        ),
    ]
