# Generated by Django 6.0 on 2026-04-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_salary_options_alter_salary_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='rate',
            new_name='base_salary',
        ),
    ]
