# Generated by Django 6.0 on 2026-04-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_rename_rate_salary_base_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField(default=0)),
                ('symbols', models.IntegerField(default=0)),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_stats', to='salary.salary')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders_count', models.IntegerField(default=0)),
                ('overdue_orders_count', models.IntegerField(default=0)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_stats', to='salary.salary')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField(default=0)),
                ('symbols', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translator_stats', to='salary.salary')),
            ],
        ),
    ]
