# Generated by Django 6.0 on 2025-12-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('work_type', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
            options={
                'db_table': 'translators',
            },
        ),
        migrations.CreateModel(
            name='TranslatorTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_page', models.FloatField(blank=True, null=True)),
                ('rate_per_action', models.FloatField(blank=True, null=True)),
                ('currency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('language_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.languagepair')),
            ],
            options={
                'db_table': 'translator_traffic',
            },
        ),
    ]
