# Generated by Django 6.0 on 2025-12-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatortraffic',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translatortraffic', to='translators.translator'),
        ),
    ]
