# Generated by Django 6.0 on 2025-12-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0002_translatortraffic_translator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatortraffic',
            old_name='translator',
            new_name='translator_id',
        ),
    ]
