# Generated by Django 6.0 on 2025-12-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0003_rename_translator_translatortraffic_translator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatortraffic',
            old_name='translator_id',
            new_name='translator',
        ),
    ]
