# Generated by Django 6.0 on 2026-01-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('translators', '0004_rename_translator_id_translatortraffic_translator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorLanguagePairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_relations', to='core.languagepair')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_pair_relations', to='translators.translator')),
            ],
            options={
                'verbose_name': 'Translator Language Pair',
                'verbose_name_plural': 'Translator Language Pairs',
                'db_table': 'translator_language_pairs',
                'unique_together': {('translator', 'language_pair')},
            },
        ),
    ]
