# Generated by Django 6.0 on 2026-01-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordercategory'),
        ('translators', '0005_translatorlanguagepairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatortraffic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator_tariffs', to='core.ordercategory'),
        ),
    ]
