# Generated by Django 6.0 on 2026-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0006_translatortraffic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
