# Generated by Django 6.0 on 2026-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0007_translator_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatortraffic',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
