# Generated by Django 6.0 on 2026-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0008_translatortraffic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
