# Generated by Django 6.0 on 2026-05-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0009_translator_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='work_type',
        ),
    ]
