# Generated by Django 6.0 on 2026-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0010_remove_translator_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatortraffic',
            name='translator',
        ),
        migrations.AddField(
            model_name='translator',
            name='traffic',
            field=models.ManyToManyField(blank=True, related_name='translators', to='translators.translatortraffic'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
