# Generated by Django 6.0 on 2026-06-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0012_translator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='currency_id',
        ),
    ]
