# Generated by Django 6.0 on 2026-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0013_remove_translator_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
