name: lingvo

services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/postgres/data
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    volumes:
      - .:/lingvo
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    command: sh /lingvo/docker-services/db_migrate.sh python manage.py runserver 0.0.0.0:8000



volumes:
  postgres_data:
